package com.upc.springcloud.dao;

import com.upc.springcloud.entity.Role;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_role
     *
     * @mbg.generated Sun Mar 22 00:32:17 CST 2020
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_role
     *
     * @mbg.generated Sun Mar 22 00:32:17 CST 2020
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_role
     *
     * @mbg.generated Sun Mar 22 00:32:17 CST 2020
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_role
     *
     * @mbg.generated Sun Mar 22 00:32:17 CST 2020
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oil_role
     *
     * @mbg.generated Sun Mar 22 00:32:17 CST 2020
     */
    int updateByPrimaryKey(Role record);
}