server:
  port: 8001

spring:
  application:
    name: cloud-test-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hqmeng.com:3306/oil?useUnicode=true&&characterEncoding=utf-8
    username:
    password:

#  mybatis.mapper-locations=classpath*:/mappers/*.xml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.upc.springclod.entity

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
#      defaultZone: http://localhost:7001/eureka
